"""
Defines the state schema for the GitGuard AI workflow.

This module contains the Pydantic models used to structure the application state,
including Pull Request metadata, the raw diff, and the list of AI-generated
review comments.
"""

from typing import List, Annotated
from pydantic import BaseModel, Field
from langgraph.graph.message import add_messages
from langchain_core.messages import AnyMessage


class PullRequestComment(BaseModel):
    """Model representing a single structured code review comment."""

    file_path: str = Field(
        ..., description="Full path of the file to comment on, relative to repo root."
    )
    line_number: int = Field(
        ..., description="Line number in the NEW file where the comment applies."
    )
    body: str = Field(
        ...,
        description="Constructive review comment text focusing on bugs or security.",
    )
    severity: str = Field(
        ..., description="Severity level: 'Critical', 'Major', 'Minor', or 'Nitpick'."
    )


class ReviewState(BaseModel):
    """
    Main graph state for the GitGuard AI agent.

    Inherits from BaseModel to support Pydantic validation and defaults.
    """

    # Messages key with reducer to track conversation history
    messages: Annotated[List[AnyMessage], add_messages] = Field(
        default_factory=list, description="Conversation history for the graph."
    )

    repo_name: str
    pr_number: int
    pr_diff: str = Field(
        default="", description="The raw text content of the Pull Request diff."
    )
    proposed_comments: List[PullRequestComment] = Field(
        default_factory=list,
        description="List of structured comments generated by the agent.",
    )
    review_approved: bool = Field(
        default=False,
        description="Flag indicating if the human has approved the review.",
    )
